### ISSUE TITLE
Album art

### ISSUE THREAD

**Issue by PaulMcleary** [androidWG/Discord.fm#20]
I'm not really sure how to use github but check this issue on a musicbee specific plugin. 

https://github.com/sll552/DiscordBee/issues/117#issue-1115766776 

Album art may be possible. I can sometimes get it to work by manually uploading the art via this method outlined here.
https://github.com/sll552/DiscordBee/issues/100#issuecomment-1013757465

**Comment by PaulMcleary** [comment]
@VelocityRa I had an album playing and switched to another album 3/4 through a song and it updated to the next song in the previous album without me scrobbling it.

**Comment by PaulMcleary** [comment]
![SmartSelect_20220511-042917_Firefox Nightly](https://user-images.githubusercontent.com/39398216/167804844-586c39e8-b9cc-479b-aa3c-1c3e2382c698.jpg)

Discord updated to read "Figaro" by Madvillain after the runtime of the previous song which would be the next song in this album

**Comment by AndroidWG** [comment]
@PaulMcleary sorry I did not receive an alert for this issue, I wish I could have seen it sooner. This is really interesting, I'll check it out this weekend.

Someone on issue 117 on MusicBee said Lsat.fm doesn't have most artworks, which in my experience is fairly true. We could try pulling from the Spotify API instead.

**Comment by androidWG** [comment]
Added in [version 0.6.2](https://github.com/androidWG/Discord.fm/releases/tag/v0.6.2-beta). Later, I'd like to maybe search the Spotify API for album art instead of just picking from Last.fm, but that'd be for a very far future version. As it is, it works perfectly and took me only around 7 or so new lines of code.
