### ISSUE TITLE
No tray icon on Windows 11 22H2 22623.875

### ISSUE THREAD

**Issue by KibSquib48** [androidWG/Discord.fm#29]
Edition	Windows 11 Home
Version	22H2
OS build	22623.875
Experience	Windows Feature Experience Pack 1000.22636.1000.0

I'm in the Windows Insider beta channel, and these builds have a remade system tray that doesn't work with some apps. It seems like this is one of them

**Comment by androidWG** [comment]
Thank you for the issue! I'll try installing the beta channel to investigate further.
Could you please upload your logs folder here? Zipping all the files and attaching to a response here works. Logs are located at `%LocalAppData%\Discord.fm`. You can also open the folder by clicking on the Open Logs Folder button in the settings window.

**Comment by androidWG** [comment]
Finished installing Windows 11 Insider build from Beta branch, but still don't have the new system tray. Trying to get my hands on it.

Overall this is likely to be a problem of pystray. I'll be creating an issue on their repo in case I find anything.

**Comment by androidWG** [comment]
Since this issue was created I've switched to using Windows 11 and on build 22621.1702 with the new system tray, I have no issues.
